drivers: misc: mediatek: connectivity: gps: Ignore unused-variable error
* ../drivers/misc/mediatek/connectivity/gps/data_link/hal/gps_dl_power_ctrl.c:501:13: error: unused variable 'done' [-Werror,-Wunused-variable]
        bool okay, done;